Sub createTube2D()

''''''''''''''''''''''''''
'3d Tube Automation
'Author@BrodyRingler
'10/16/2014

'All dimension lengths are in centimeters and angles are in radians
''''''''''''''''''''''''''

'Import parameters from excel
Dim bendRadius As Double
bendRadius = 5  'import bend radius
   
'Create new part doc and define initial settings
Dim invApp As Inventor.Application
Dim partDoc As Inventor.PartDocument
Dim partDef As Inventor.PartComponentDefinition
Dim xyPlane As Inventor.WorkPlane
Dim yzPlane As Inventor.WorkPlane
Dim sketchXY As Inventor.PlanarSketch
Dim sketchYZ As Inventor.PlanarSketch
Dim sketchPath As Inventor.Sketch3D
Dim transGeo As Inventor.TransientGeometry
Dim autobend As Inventor.Sketch3DSettings
    Set invApp = GetObject(, "Inventor.Application")
    Set partDoc = invApp.Documents.Add(Inventor.DocumentTypeEnum.kPartDocumentObject)
    'partDoc.Save   'use this to select file location of new part
    Set partDef = partDoc.ComponentDefinition
    Set xyPlane = partDef.WorkPlanes.Item(3)
    Set yzPlane = partDef.WorkPlanes.Item(1)
    Set sketchXY = partDef.Sketches.Add(xyPlane, False)
    Set sketchYZ = partDef.Sketches.Add(yzPlane, False)
    Set sketchPath = partDef.Sketches3D.Add()
    Set transGeo = invApp.TransientGeometry
    Set autobend = partDoc.Sketch3DSettings
    autobend.AutoBendRadius = bendRadius
    

'Create multidimensional point array for path lines
Dim dimensionArray(20, 2) As Double
Dim rowIndex As Integer
Dim max As Integer

rowIndex = 0
max = 2
maxLine = max - 1
maxBends = maxLine - 1

x1 = 0
y1 = 0
z1 = 0
x2 = 100
y2 = 0
z2 = 0
x3 = 100
y3 = 40
z3 = 0

    dimensionArray(rowIndex, 0) = x1 'range for x values
    dimensionArray(rowIndex, 1) = y1 'range for y values
    dimensionArray(rowIndex, 2) = z1 'range for z values
    
    rowIndex = rowIndex + 1
    
    dimensionArray(rowIndex, 0) = x2 'range for x values
    dimensionArray(rowIndex, 1) = y2 'range for y values
    dimensionArray(rowIndex, 2) = z2 'range for z values
    
    rowIndex = rowIndex + 1
    
    dimensionArray(rowIndex, 0) = x3 'range for x values
    dimensionArray(rowIndex, 1) = y3 'range for y values
    dimensionArray(rowIndex, 2) = z3 'range for z values

    'Create points for path lines
    Dim pointArray(20) As Inventor.SketchPoint3D
    Dim pointIndex As Integer
    Dim points As Inventor.SketchPoints3D
        pointIndex = 0
        Set points = sketchPath.SketchPoints3D
        For pointIndex = 0 To max
            Set pointArray(pointIndex) = points.Add(transGeo.CreatePoint(dimensionArray(pointIndex, 0), dimensionArray(pointIndex, 1), dimensionArray(pointIndex, 2)))
        Next

'Create lines for sweep path
Dim lineArray(19) As Inventor.SketchLine3D
Dim lineIndex As Integer
Dim lines As Inventor.SketchLines3D
    lineIndex = 0
    pointIndex = 0
    Set lines = sketchPath.SketchLines3D
    Set lineArray(lineIndex) = lines.AddByTwoPoints(pointArray(pointIndex), pointArray(pointIndex + 1))
        For lineIndex = 1 To maxLine
            pointIndex = pointIndex + 1
            Set lineArray(lineIndex) = lines.AddByTwoPoints(pointArray(pointIndex), pointArray(pointIndex + 1))
        Next

'Create bends on sweep path
'Dim bendArray(18) As Inventor.SketchArc3D
'Dim bendIndex As Integer
'Dim bends As Inventor.SketchArcs3D
    'bendIndex = 0
    'lineIndex = 0
    'Set bends = sketchPath.SketchArcs3D
        'For bendIndex = 0 To maxBends
            'Set bendArray(bendIndex) = bends.AddAsBend(lineArray(lineIndex), lineArray(lineIndex + 1), bendRadius)
            'Call lineArray(lineIndex + 1).StartSketchPoint.ConnectTo(lineArray(lineIndex).EndSketchPoint)
            'lineIndex = lineIndex + 1
        'Next
        
'Create shapes for sweep profile
Dim profiles As Inventor.SketchCircles
    Set profiles = sketchYZ.SketchCircles
    Set profileOuter = profiles.AddByCenterRadius(transGeo.CreatePoint2d(0, 0), 3)
    Set profileInner = profiles.AddByCenterRadius(transGeo.CreatePoint2d(0, 0), 2.5)

'Create sweep feature to generate tube part
    Set sweepPath = partDef.Features.CreatePath(lineArray(0))
    Set sweepProfile = sketchYZ.profiles.AddForSolid(True)
    Set sweepTube = partDef.Features.SweepFeatures.AddUsingPath(sweepProfile, sweepPath, PartFeatureOperationEnum.kNewBodyOperation, SweepProfileOrientationEnum.kNormalToPath)

MsgBox ("procedure was successful")



End Sub
